from  app.Agents.Main_agent.state import InvestigationState,Claim
from typing import List
from langgraph.types import Send

def hive_assesment_fanout(state:InvestigationState) -> List[Send]:
    """
    Fan-Out Conditional Edge:
    Reads the list of tasks generated by the orchestrator and triggers 
    an independent, parallel execution of 'worker_node' for every task.
    """
    claims: List[Claim] = state['claims']

    # For each task in the plan, dispatch a Send object to the worker node
    return [
        Send(
            node="hive_assesment_analysis_worker",  # Target node name registered in the graph
            arg={
                'claim':claim['text'],'id':claim['id'],'user_input_id':state['thread_id']
            }
        )
        for claim in claims
    ]
