from  app.Agents.Main_agent.state import InvestigationState,Claim
from typing import List
from langgraph.types import Send

def News_router_fan_out(state:InvestigationState) -> List[Send]|str:
    """
    Fan-Out Conditional Edge:
    Reads the list of tasks generated by the orchestrator and triggers 
    an independent, parallel execution of 'worker_node' for every task.
    """
    claims: List[Claim] = state['claims']
    th=state.get("th",0.75)
    print("news_search_router")
    # For each task in the plan, dispatch a Send object to the worker node
        
    return [
            Send(
                node="news_search_router",  # Target node name registered in the graph
                arg={
                    'claim':claim['text'],'id':claim['id'],'th':th,'user_input_id':state['thread_id']
                }
            )
            for claim in claims
        ]
    