from  app.Agents.Main_agent.state import InvestigationState,Claim
from typing import List
from langgraph.types import Send

def pubmed_evidence_fan_out(state:InvestigationState) -> List[Send]|str:
    """
    Fan-Out Conditional Edge:
    Reads the list of tasks generated by the orchestrator and triggers 
    an independent, parallel execution of 'worker_node' for every task.
    """
    claims: List[Claim] = state['claims']
    th=state.get("th",0.75)
    print("who_evidence_fan_out")
    # For each task in the plan, dispatch a Send object to the worker node
        
    if(state['category']=="HEALTH" or state['category']=="SCIENCE" ):
        return [
            Send(
                node="pubmed_evidence_worker",  # Target node name registered in the graph
                arg={
                    'claim':claim['text'],'id':claim['id'],'th':th,'user_input_id':state['thread_id']
                }
            )
            for claim in claims
        ]
    else:
        return "claim_assesment"